version: '3.2'
services:

  localstack:
    image: localstack/localstack
    container_name: localstack_dynamotest_ts
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb, s3
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_KEY=xyz
      - AWS_REGION=us-east-1
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - ./etc/localstack.d:/docker-entrypoint-initaws.d
